# Trying stuff

In [6]:
import dhlab as dh
from IPython.display import HTML, Markdown
import os
import sqlite3
import pandas as pd

You may add your own css for displaying the notebook

In [7]:
dh.css("medium.css")

In [8]:
!ls /mnt/disk2/NB-ngram-assoc/

association-notes.html	 galakser.py		   stop_words_basex_ft.txt
avis-bigram-all-row.db	 galaxy2gexf.py		   top100.csv
avis-bigram-one-row.db	 galaxy2graphml.py	   top100first.txt
avis_entropy_all.csv	 kun-info-viten.csv	   trigram-all-row.db
avis_entropy.csv	 kunnskap-viten-info.csv   trigram-entiteter-avis.csv
avis-trigram-all-row.db  ngram_parser.ipynb	   trigram-entiteter-avis.db
avis-trigram-one-row.db  ngram_viewer_ndvd3.ipynb  trigram-one-row.db
avis-unigram-all-row.db  paratakse.txt		   unigram-all-row.db
avis-unigram-one-row.db  parse_nor.py		   unigram-one-row.db
bigram-all-row.db	 parse.py		   untitled
bigram-one-row.db	 parse.py~		   updates.sql
d3force.py		 __pycache__
David.ipynb		 sqlite3_query_ft.ipynb

In [9]:
ngram_root = "/mnt/disk2/NB-ngram-assoc/"

In [10]:
with open("/mnt/disk2/NB-ngram-assoc/association-notes.html") as f:
    x = f.read()

In [11]:
uni = "/mnt/disk2/NB-ngram-assoc/unigram-one-row.db"
bi = "/mnt/disk2/NB-ngram-assoc/bigram-one-row.db"
tri = "/mnt/disk2/NB-ngram-assoc/trigram-one-row.db"

In [12]:
def query(db, sql, params=()):
    with sqlite3.connect(db) as con:
        cur = con.cursor()
        res = cur.execute(sql, params).fetchall()
    return res

In [13]:
query(tri, "select * from sqlite_master")

[('table',
  'trigram',
  'trigram',
  2,
  'CREATE TABLE trigram (freq int, lang varchar, first varchar, second varchar, third varchar, json text, assoc float)'),
 ('index',
  '_lfstf_',
  'trigram',
  7345631,
  'CREATE INDEX _lfstf_ on trigram(lang,first,second,third,freq)'),
 ('index',
  '_lf_',
  'trigram',
  8176254,
  'CREATE INDEX _lf_ on trigram(lang,freq)'),
 ('index',
  '_lstf_',
  'trigram',
  8581773,
  'CREATE INDEX _lstf_ on trigram (lang,second,third,freq)'),
 ('index',
  '_ltf_',
  'trigram',
  9271437,
  'CREATE INDEX _ltf_ on trigram (lang,third,freq)'),
 ('index',
  '_lftf_',
  'trigram',
  9816345,
  'CREATE INDEX _lftf_ on trigram (lang,first,third,freq)'),
 ('index',
  '_lfsta_',
  'trigram',
  11071163,
  'CREATE INDEX _lfsta_ on trigram (lang, first, second, third, assoc)'),
 ('index',
  '_la_',
  'trigram',
  12091504,
  'CREATE INDEX _la_ on trigram (lang, assoc)'),
 ('index',
  '_lsta_',
  'trigram',
  12684194,
  'CREATE INDEX _lsta_ on trigram (lang, second, third, assoc)'),
 ('index',
  '_lta_',
  'trigram',
  13563091,
  'CREATE INDEX _lta_ on trigram (lang, third, assoc)'),
 ('index',
  '_lfta_',
  'trigram',
  14295455,
  'CREATE INDEX _lfta_ on trigram (lang,first, third, assoc)'),
 ('index',
  '_lfa_',
  'trigram',
  15168956,
  'CREATE INDEX _lfa_ on trigram (lang,first,assoc)'),
 ('index',
  '_lsa_',
  'trigram',
  15899063,
  'CREATE INDEX _lsa_ on trigram (lang,second,assoc)')]

In [14]:
def search(expr, lang = 'nob', limit = 10):
    mapping = {0:"first", 1:"second", 2:"third"}
    func_map = {0:unigrams, 1:bigrams, 2:trigrams}
    kwargs = dict()
    for i,e in enumerate([x.strip() for x in expr.split()]):
        if i > 2:
            i = 2
            break
        if e != "*":
            kwargs[mapping.get(i)] = e
    return func_map[i](lang = lang, limit=limit, **kwargs)
            
        


def trigrams(first=None, second=None, third=None, limit = 10, lang='nob', order='assoc'):
    a = locals()
    lang = a['lang']
    limit = a['limit']
    order = a['order']
    qs = [f"{k} = '{a[k]}'" for k in a if a[k] is not None and k in ['first','second', 'third']]
    q = ' and '.join(qs)
    if q != "":
        q = " and " + q
    res = query(tri, f"""
        select first, second, third, freq, assoc 
        from trigram 
        where 
            lang = '{lang}' 
            {q} 
        order by {order} 
        desc 
        limit {limit}""")
    return pd.DataFrame(res, columns="first second third freq assoc".split())

def bigrams(first=None, second=None, limit = 10, lang='nob', order='pmi'):
    a = locals()
    lang = a['lang']
    limit = a['limit']
    order = a['order']
    qs = [f"{k} = '{a[k]}'" for k in a if a[k] is not None and k in ['first','second', 'third']]
    q = ' and '.join(qs)
    if q != "":
        q = " and " + q
    res = query(bi, f"""
        select first, second, freq, pmi 
        from bigram 
        where 
            lang = '{lang}' 
            {q} 
        order by {order} 
        desc 
        limit {limit}""")
    return pd.DataFrame(res, columns="first second freq pmi".split())

def unigrams(first=None, limit = 10, lang='nob', order='freq'):
    a = locals()
    lang = a['lang']
    limit = a['limit']
    order = a['order']
    qs = [f"{k} = '{a[k]}'" for k in a if a[k] is not None and k in ['first','second', 'third']]
    q = ' and '.join(qs)
    if q != "":
        q = " and " + q
    res = query(uni, f"""
        select first, freq 
        from unigram 
        where 
            lang = '{lang}' 
            {q} 
        order by {order} 
        desc 
        limit {limit}""")
    return pd.DataFrame(res, columns="first freq".split())

In [31]:
bigrams(second='gående', order='pmi',  limit=50).apply(lambda x: x['first'][-1] != '-')

               first  second   freq        pmi
0            videre-  gående    567  54.450370
1               N-S-  gående    134  49.184564
2                kom  gående  20396  48.752277
3          nord-sør-  gående    239  47.886380
4               Ø-V-  gående     75  44.571862
5          øst-vest-  gående    133  39.628158
6              fore-  gående    229  36.828881
7             NV-SØ-  gående     36  36.402415
8             NØ-SV-  gående     31  34.481320
9             holdes  gående    885  33.983719
10          gjennom-  gående    129  32.380030
11         nord-syd-  gående     40  31.885301
12            SØ-NV-  gående     19  31.701789
13             komme  gående   3205  31.321230
14            kommer  gående   3969  31.255196
15              pike  gående    525  30.586996
16               N-S  gående     66  30.577586
17          nord-sør  gående     78  30.268794
18          samtalen  gående    473  29.915442
19           Videre-  gående     42  29.457523
20          langsomt  gående    683  28.860148
21              fore  gående    318  28.439451
22             doms-  gående     48  28.358045
23          NNØ-SSV-  gående     15  28.231195
24          øst-vest  gående     68  28.128437
25           driften  gående    312  27.360017
26           spillet  gående    290  27.316977
27               ble  gående   6527  25.844381
28           samtale  gående    365  25.840257
29               det  gående  23638  25.423596
30    konversasjonen  gående     48  24.894676
31               bli  gående   2719  24.628609
32              blir  gående   3509  24.047485
33         forstyrre  gående    135  24.032705
34          nord-syd  gående     32  24.007114
35         vest-øst-  gående     14  23.153806
36            affære  gående     94  23.009394
37  nordøst-sørvest-  gående      9  22.787084
38             NV-SØ  gående     19  22.083463
39             holdt  gående    936  21.718298
40            praten  gående     59  21.685579
41              inn-  gående    126  21.383190
42          VNV-ØSØ-  gående      8  20.668418
43              blev  gående    957  20.528686
44              mann  gående    807  20.076713
45            forut-  gående     24  19.797989
46            kampen  gående    221  19.642954
47             sakte  gående    152  19.540637
48      forretningen  gående     90  19.149371
49            kommet  gående    627  18.659726

In [111]:
trigrams(third='persille',  limit=50)

           first       second     third  freq      assoc
0   spiseskefuld    finhakket  persille    23  26.271626
1       spiseske    finhakket  persille   230  25.876339
2     spiseskeer    finhakket  persille    23  23.999892
3          teske    finhakket  persille    37  23.609906
4             ss   finklippet  persille    84  23.030260
5          Dryss       hakket  persille   163  22.814763
6       spiseske       hakket  persille    28  22.761524
7      spiseskje    finhakket  persille    30  22.616359
8      spiseskje       hakket  persille    66  22.395876
9             ss    finhakket  persille   723  22.356944
10         Dryss    finhakket  persille    37  22.340871
11          Strø       hakket  persille    44  22.029948
12            ss       hakket  persille  1423  22.025117
13     tilsættes    finhakket  persille    15  22.006365
14          Strø    finhakket  persille    13  21.819648
15   spiseskjeer       hakket  persille    35  21.818086
16         dryss       hakket  persille    44  21.545063
17   spiseskjeer    finhakket  persille     8  21.351120
18            dl   finklippet  persille    11  20.997616
19            dl    finhakket  persille   164  20.873679
20          bunt       hakket  persille    27  20.572433
21        pepper       hakket  persille    99  20.315338
22       Tilsett    finhakket  persille    15  20.303167
23             f     inhakket  persille    19  20.220881
24          strø       hakket  persille    21  20.118618
25       Tilsett       hakket  persille    32  20.051912
26            dl       hakket  persille   195  20.037871
27           sp.    finhakket  persille    32  19.923821
28        pepper    finhakket  persille    16  19.501747
29            ts       hakket  persille    72  19.463752
30     tilsettes       hakket  persille    23  19.412140
31       rikelig       hakket  persille    54  19.379359
32       tilsett       hakket  persille    11  19.377335
33            ts    finhakket  persille    22  19.287069
34            ss        klipt  persille    11  19.233944
35       tilsatt       hakket  persille    33  19.114600
36             2  ssfinhakket  persille    17  18.984079
37          fint      hakkede  persille    20  18.921920
38        hakket        frisk  persille    65  18.700389
39            ss      klippet  persille    46  18.600623
40          kopp       hakket  persille    19  18.480200
41       rikelig    finhakket  persille     8  18.478757
42           sp.       hakket  persille    19  18.393583
43     finhakket        frisk  persille    15  18.242992
44         frisk       hakket  persille    28  17.858206
45             1     spiseske  persille    86  17.763758
46          lidt    finhakket  persille     9  17.684560
47         liten         bunt  persille    75  17.631705
48             1         bunt  persille   595  17.545249
49           med      fritert  persille    97  17.420185

In [95]:
unigrams(  limit=50)

    first       freq
0       .  579382440
1       ,  471880905
2      og  259886630
3       i  225005888
4     som  128038992
5     det  127565461
6      er  123343894
7      av  122090298
8     til  121192030
9      en  116360555
10    for   95899199
11     på   95839387
12     at   93020220
13      å   87577929
14    med   85341825
15      -   82978359
16      )   71492424
17    den   70750565
18     de   68605843
19    var   68067928
20   ikke   67784910
21      (   61148070
22      :   55785327
23    har   52151766
24     et   50863444
25     om   50533570
26    han   47049244
27      »   46888112
28      «   46790585
29    Det   39136956
30    kan   38196138
31    fra   36155270
32    seg   35863548
33      ?   34124584
34      —   33760374
35    jeg   33707783
36      I   31712505
37  hadde   30225156
38  eller   29206541
39     så   28430919
40    ved   27373999
41     vi   26966557
42      "   26824082
43      1   24841539
44      /   24636523
45    men   24560995
46      2   24285677
47    ble   23195184
48      3   21088925
49      ;   21081050

In [77]:
query(tri, 'CREATE INDEX _lsa_ on trigram (lang,second,assoc)')

[]